replicaCount: 2
image:
  repository: <YOUR_DOCKER_REGISTRY>/moderation-service
  tag: "{{ .Values.image.tag }}"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  hosts:
    - host: moderation-service.<DOMAIN>
      paths:
        - path: /
          pathType: Prefix
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
