name: Promote to Production

on:
  workflow_run:
    workflows: ["Deploy to Staging"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Authenticate to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG_PROD }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
      - name: Deploy to Production
        run: |
          for chart in helm-charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              name=$(basename $chart)
              helm upgrade --install $name $chart \
                --namespace production \
                --values helm-charts/values.global.yaml \
                --wait
            fi
          done